[build]
publish = "."
functions = "netlify/functions"

[build.environment]
SECRETS_SCAN_ENABLED = "false"

[functions]
directory = "netlify/functions"
node_bundler = "esbuild"

# Increase timeout for image generation (Promptchan can take 15-20 seconds)
[functions."selira-generate-custom-image"]
timeout = 30

# Increase timeout for companion creation (includes avatar generation)
[functions."selira-create-companion"]
timeout = 60

# Scheduled function to download Replicate URLs every 8 hours
[functions."download-replicate-avatars-scheduled"]
schedule = "0 */8 * * *"

# Headers for LLM crawling files
[[headers]]
for = "/llms.txt"
[headers.values]
Content-Type = "text/plain; charset=utf-8"
Cache-Control = "public, max-age=3600"

[[headers]]
for = "/mcp.json"
[headers.values]
Content-Type = "application/json; charset=utf-8"
Cache-Control = "public, max-age=3600"
Access-Control-Allow-Origin = "*"

[[headers]]
for = "/.well-known/*"
[headers.values]
Content-Type = "application/json; charset=utf-8"
Cache-Control = "public, max-age=3600"
Access-Control-Allow-Origin = "*"
