[build]
publish = "."
functions = "netlify/functions"

[build.environment]
SECRETS_SCAN_ENABLED = "false"

[functions]
directory = "netlify/functions"
node_bundler = "esbuild"

# Increase timeout for image generation (Promptchan can take 15-20 seconds)
# Netlify Pro max is 26 seconds
[functions."selira-generate-custom-image"]
timeout = 26

# Increase timeout for companion creation (includes avatar generation)
# Netlify Pro max is 26 seconds
[functions."selira-create-companion"]
timeout = 26

# Scheduled function to download external URLs (Replicate/ImgBB/googleapis) to local storage
# Runs once per day at 3:00 AM UTC to save credits
[functions."download-replicate-avatars-scheduled"]
schedule = "0 3 * * *"

# Cache static assets to reduce bandwidth and web requests
[[headers]]
for = "/js/*.js"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/css/*.css"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/avatars/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/*.html"
[headers.values]
Cache-Control = "public, max-age=3600"

# Headers for LLM crawling files
[[headers]]
for = "/llms.txt"
[headers.values]
Content-Type = "text/plain; charset=utf-8"
Cache-Control = "public, max-age=3600"

[[headers]]
for = "/mcp.json"
[headers.values]
Content-Type = "application/json; charset=utf-8"
Cache-Control = "public, max-age=3600"
Access-Control-Allow-Origin = "*"

[[headers]]
for = "/.well-known/*"
[headers.values]
Content-Type = "application/json; charset=utf-8"
Cache-Control = "public, max-age=3600"
Access-Control-Allow-Origin = "*"
