[build]
publish = "."
functions = "netlify/functions"

[build.environment]
SECRETS_SCAN_ENABLED = "false"

[functions]
directory = "netlify/functions"
node_bundler = "esbuild"

# Scheduled function to download Replicate URLs every 8 hours
[[functions]]
  name = "download-replicate-avatars-scheduled"
  schedule = "0 */8 * * *"
